In [2]:
import pandas as pd

In [ ]:
# csv
# 数据的导入
df = pd.read_csv('data/employees.csv')
df_t = df.tail()
#数据的导出
df_t.to_csv('data/e_tail.csv')

     employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0

In [ ]:
# json
# 数据的导入
    # 1.
df = pd.read_json('data/test.json')  # 直接导入格式会乱
    # 2.
import json
with open('data/test.json') as f:
    data = json.load(f)
df = pd.DataFrame(data['users'])
df

   id name  age                 email  is_active   join_date
0   1   张三   28  zhangsan@example.com       True  2022-03-15
1   2   李四   35      lisi@example.com      False  2021-11-02
2   3   王五   24    wangwu@example.com       True  2023-01-20

In [20]:
# 缺失值的处理
# nan: not a number
import pandas as pd
import numpy as np
s = pd.Series([1,2,np.nan,None,pd.NA])
s
df = pd.DataFrame([[1,2,3,np.nan],[4,5,6,None],[7,8,9,33]])
df

   0  1  2     3
0  1  2  3   NaN
1  4  5  6   NaN
2  7  8  9  33.0

In [16]:
# 查看是否是缺失值
print(s.isna())
print(s.isnull())

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool

In [ ]:
# 剔除缺失值
print(s.dropna())  # 只删除单个缺失值
print(df.dropna())  # 只要有缺失值就会删除一整行
print(df.dropna(how = 'all'))  # 若一行中所有的值都是缺失值，才删除一整行数据
print(df.dropna(thresh=2))  # 若至少有n个值不是缺失值，就保留
print(df.dropna(axis=1))  # 剔除一整列
print(df.dropna(subset=[3]))  # 指定检查某一列的缺失值 如果有就删除一整行

0    1
1    2
dtype: object
   0  1  2     3
2  7  8  9  33.0
   0  1  2     3
0  1  2  3   NaN
1  4  5  6   NaN
2  7  8  9  33.0
   0  1  2     3
0  1  2  3   NaN
1  4  5  6   NaN
2  7  8  9  33.0
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9
1111111    0  1  2     3
2  7  8  9  33.0

In [ ]:
# 填充缺失值
df = pd.read_csv('data/weather_withna.csv')
df.tail()
df.isna().sum(axis=0)
print(df.fillna({'temp_max':20,'wind':2.5}).tail()) #使用字典指定列填充固定值
print(df.fillna(df[['wind']].mean()).tail())  # 使用统计值来填充
print(df.ffill().tail())  # 使用前面的值相邻值填充
print(df.bfill().tail())  # 使用后面的值相邻值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind weather
1456  2015-12-27            NaN       NaN       NaN  3.242055     NaN
1457  2015-12-28            NaN       NaN       NaN  3.242055     NaN
1458  2015-12-29            NaN       NaN       NaN  3.242055     NaN
1459  2015-12-30            NaN       NaN       NaN  3.242055     NaN
1460  2015-12-31           20.6      12.2       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain