In [1]:
import pandas as pd

In [2]:
data = {
    'ID':[1,2],
    'name':['alice','bob'],
    'math':[90,85],
    'english':[88,92],
    'science':[95,89]
}
df = pd.DataFrame(data)

In [ ]:
# 1. 转置
df.T

   ID   name  math  english  science
0   1  alice    90       88       95
1   2    bob    85       92       89

In [ ]:
df  # 宽表
# 宽表变长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values('name')

   ID   name       科目  分数
0   1  alice     math  90
2   1  alice  english  88
4   1  alice  science  95
1   2    bob     math  85
3   2    bob  english  92
5   2    bob  science  89

In [12]:
# 长表变宽表
pd.pivot(df2,index=['ID','name'],columns='科目',values='分数')

科目        english  math  science
ID name
1  alice       88    90       95
2  bob         92    85       89

In [16]:
data = {
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'math':[90,85],
    'english':[88,92],
    'science':[95,89]
}
df = pd.DataFrame(data)

In [18]:
# 分列 (把一个列分成两列)
df[['first','last']] = df['name'].str.split(" ",expand=True)
df

   ID         name  math  english  science  first   last
0   1  alice smith    90       88       95  alice  smith
1   2    bob smith    85       92       89    bob  smith

In [23]:
# 分列高压和低压
df = pd.read_csv('data/sleep.csv')
df = df[['person_id','blood_pressure']]
df[['high_blood_pressure','short_blood_pressure']] = df['blood_pressure'].str.split('/',expand=True)
df['high_blood_pressure'] = df['high_blood_pressure'].astype('int64')
df['short_blood_pressure'] = df['short_blood_pressure'].astype('int64')
df

     person_id blood_pressure  high_blood_pressure  short_blood_pressure
0            1         124/70                  124                    70
1            2         131/86                  131                    86
2            3         122/70                  122                    70
3            4         124/72                  124                    72
4            5         133/78                  133                    78
..         ...            ...                  ...                   ...
395        396         118/66                  118                    66
396        397         132/80                  132                    80
397        398         125/76                  125                    76
398        399         130/75                  130                    75
399        400         118/70                  118                    70

[400 rows x 4 columns]